-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 17:20:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdfestejar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdfestejar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdfestejar` DEFAULT CHARACTER SET utf8 ;
USE `bdfestejar` ;

-- -----------------------------------------------------
-- Table `bdfestejar`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdfestejar`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nomecompleto` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfestejar`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdfestejar`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeprod` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descriprod` VARCHAR(300) NOT NULL,
  `contato` INT(11) NOT NULL,
  `estado` VARCHAR(18) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Pessoa_idx` (`Pessoa_idPessoa` ASC) ,
  CONSTRAINT `fk_Produto_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdfestejar`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfestejar`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdfestejar`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  INDEX `fk_Avaliacao_Produto1_idx` (`Produto_idProduto` ASC) ,
  CONSTRAINT `fk_Avaliacao_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bdfestejar`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `bdfestejar`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
